import type { Snapshot } from "./types";

export const DEMO_SNAPSHOT: Snapshot = {
  type: "snapshot",
  room: {
    id: "7A3F",
    status: "playing",
    maxPlayers: 2,
    connectedPlayers: 2,
    reconnectTimeoutSeconds: 120,
    createdAt: "2026-07-28T10:30:00Z",
  },
  you: {
    id: "demo-you",
    index: 1,
    nickname: "Klio",
  },
  players: [
    {
      id: "demo-opponent",
      index: 0,
      nickname: "Михаил",
      connected: true,
      isYou: false,
      cardCount: 6,
      placement: 0,
      isDurak: false,
    },
    {
      id: "demo-you",
      index: 1,
      nickname: "Klio",
      connected: true,
      isYou: true,
      cardCount: 8,
      hand: [7, 8, 24, 25, 30, 31, 43, 44],
      placement: 0,
      isDurak: false,
    },
  ],
  game: {
    version: 9,
    phase: "defense",
    dealer: 0,
    mainAttacker: 0,
    defender: 1,
    eligibleAttackers: 1,
    passedAttackers: 0,
    attackCount: 3,
    attackLimit: 6,
    deckCount: 38,
    discardCount: 4,
    trump: "hearts",
    trumpCard: 31,
    transferLocked: true,
    takeDeclared: false,
    draw: false,
    table: [
      { slot: 0, attack: 7, defense: null },
      { slot: 1, attack: 18, defense: 31 },
      { slot: 2, attack: 11, defense: 24 },
    ],
    legalActions: [
      { kind: "defend", card: 8, targetSlot: 0 },
      { kind: "defend", card: 30, targetSlot: 0 },
      { kind: "defend", card: 31, targetSlot: 0 },
      { kind: "take", card: null, targetSlot: null },
    ],
    technicalLoser: null,
  },
  events: [
    {
      id: "event-1",
      kind: "action",
      message: "Михаил атакует 9♣.",
      at: "2026-07-28T10:35:00Z",
    },
    {
      id: "event-2",
      kind: "action",
      message: "Klio отбивает картой Q♦.",
      at: "2026-07-28T10:34:40Z",
    },
    {
      id: "event-3",
      kind: "action",
      message: "Михаил подкидывает 7♥.",
      at: "2026-07-28T10:34:10Z",
    },
    {
      id: "event-4",
      kind: "system",
      message: "Раунд начался.",
      at: "2026-07-28T10:34:00Z",
    },
  ],
  rulesVersion: "chinese-durak/0.2.1-draft",
};
